# Generated by Django 3.2.16 on 2023-01-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名子')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heros', to='books.bookinfo', verbose_name='书名')),
            ],
        ),
    ]
