# Generated by Django 3.2.16 on 2023-01-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_heroinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heroes', to='books.bookinfo', verbose_name='书名'),
        ),
    ]
